######################################################################
# Automatically generated by qmake (3.0) ?? 2? 28 17:15:49 2016
######################################################################

TEMPLATE = app
TARGET = disk-usage-analyzer-master
INCLUDEPATH += .

# Input
HEADERS += MyFileSystemWalker.h
SOURCES += main.cpp MyFileSystemWalker.cpp
RESOURCES += components.qrc data.qrc
