######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 11 12:03:22 2014
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += unittests.cpp \
    ../parser.cpp \
    ../recorder.cpp \


HEADERS += ../parser.h \
        ../message.h \
        ../recorder.h \

