#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   exit 1
fi

echo "Remove manPagesGui"
for I in share/manpagesgui share/man/man1/manpagesgui.1.gz share/man/fr/man1/manpagesgui.1.gz bin/manpagesgui share/applications/manpagesgui.desktop
do
  rm -r "/usr/$I"
done

echo
echo "Uninstallation Complete"
